### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by acrolink** [d-sauer/tests#1]
Would you please tell me what is the equivalent commands under Maven for:

```
In first window, start gradle build with continous flag: gradle build -continuous
In second terminal start Spring Boot Server gradle bootRun
```

Thank you..

**Comment by d-sauer** [comment]
I assume that you are referring to [this article](https://github.com/d-sauer/blog/blob/master/2015/spring_boot_dev_tools_with_gradle/index.md).

As I know there is not equivalent in Maven for `gradle -continuos` or `gradle -t` flag, to detect changes in codebase and then execute same set of commands again.
You have something similar with Maven Jetty plugin: [scanIntervalSeconds](http://stackoverflow.com/questions/27701104/how-to-make-maven-automatically-recompile-if-changes-are-detected).

**Comment by acrolink** [comment]
Thank you @d-sauer
